"""Cross-validation tests — verify Python SDK produces identical results to Rust.

Reads test_vectors.json generated by Rust (trustchain-core/tests/cross_validation.rs).
Run the Rust test first to generate vectors:
    cd trustchain && cargo test --test cross_validation

Then run these tests:
    cd trustchain-py && python -m pytest tests/test_cross_validation.py -v
"""

import hashlib
import json
from pathlib import Path

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from trustchain.identity import Identity
from trustchain.halfblock import (
    HalfBlock,
    compute_block_hash,
    create_half_block,
    verify_block,
)

VECTORS_PATH = Path(__file__).resolve().parent.parent.parent / "trustchain" / "test_vectors.json"


@pytest.fixture(scope="module")
def vectors():
    if not VECTORS_PATH.exists():
        pytest.skip(
            f"test_vectors.json not found at {VECTORS_PATH}. "
            "Run `cargo test --test cross_validation` in the trustchain/ repo first."
        )
    with open(VECTORS_PATH) as f:
        return json.load(f)


def identity_from_seed(seed_hex: str) -> Identity:
    """Create an Identity from a 32-byte seed (matching Rust's Identity::from_bytes)."""
    seed_bytes = bytes.fromhex(seed_hex)
    private_key = Ed25519PrivateKey.from_private_bytes(seed_bytes)
    return Identity(private_key=private_key)


# ---------------------------------------------------------------------------
# 1. Identity from seed → same pubkey
# ---------------------------------------------------------------------------


class TestIdentityVectors:
    def test_identity_from_seed(self, vectors):
        for vec in vectors["identity_vectors"]:
            identity = identity_from_seed(vec["seed"])
            assert identity.pubkey_hex == vec["pubkey"], (
                f"Seed {vec['seed'][:16]}...: "
                f"Python={identity.pubkey_hex[:16]}... vs Rust={vec['pubkey'][:16]}..."
            )


# ---------------------------------------------------------------------------
# 2. Canonical hash → same SHA-256
# ---------------------------------------------------------------------------


class TestHashVectors:
    def test_canonical_hash(self, vectors):
        for vec in vectors["hash_vectors"]:
            # Python canonical: json.dumps with sort_keys=True, separators=(",", ":")
            canonical = json.dumps(vec["input"], sort_keys=True, separators=(",", ":"))
            sha256 = hashlib.sha256(canonical.encode()).hexdigest()

            assert canonical == vec["canonical"], (
                f"Canonical mismatch: Python={canonical!r} vs Rust={vec['canonical']!r}"
            )
            assert sha256 == vec["sha256"], (
                f"Hash mismatch: Python={sha256} vs Rust={vec['sha256']}"
            )


# ---------------------------------------------------------------------------
# 3. Block hash matches
# ---------------------------------------------------------------------------


class TestBlockVectors:
    def test_block_hash_matches(self, vectors):
        for vec in vectors["block_vectors"]:
            identity = identity_from_seed(vec["creator_seed"])

            # Verify pubkey matches.
            assert identity.pubkey_hex == vec["expected_public_key"]

            block = create_half_block(
                identity=identity,
                sequence_number=vec["sequence_number"],
                link_public_key=identity_from_seed(vec["counterparty_seed"]).pubkey_hex,
                link_sequence_number=vec["link_sequence_number"],
                previous_hash=vec["previous_hash"],
                block_type=vec["block_type"],
                transaction=vec["transaction"],
                timestamp=vec["timestamp"],
            )

            assert block.block_hash == vec["expected_block_hash"], (
                f"Block hash mismatch: Python={block.block_hash[:16]}... "
                f"vs Rust={vec['expected_block_hash'][:16]}..."
            )
            assert block.signature == vec["expected_signature"], (
                f"Signature mismatch: Python={block.signature[:16]}... "
                f"vs Rust={vec['expected_signature'][:16]}..."
            )
            assert verify_block(block), "Block verification failed"


# ---------------------------------------------------------------------------
# 4. Trust scores match
# ---------------------------------------------------------------------------


class TestTrustVectors:
    def test_trust_scores_match(self, vectors):
        from trustchain.blockstore import MemoryBlockStore
        from trustchain.trust import TrustEngine

        for vec in vectors["trust_vectors"]:
            id_a = identity_from_seed(vec["seed_a"])
            id_b = identity_from_seed(vec["seed_b"])

            # Use a shared store (matching Rust's cross_validation.rs).
            # Both proposals and agreements go into the same store so that
            # get_linked_block() can find bilateral pairs for completion_rate.
            store = MemoryBlockStore()

            base_ts = vec["base_timestamp"]
            step = vec["timestamp_step"]
            genesis = "0" * 64

            prev_a = genesis
            prev_b = genesis
            for i in range(vec["n_interactions"]):
                ts = base_ts + i * step
                proposal = create_half_block(
                    identity=id_a,
                    sequence_number=i + 1,
                    link_public_key=id_b.pubkey_hex,
                    link_sequence_number=0,
                    previous_hash=prev_a,
                    block_type="proposal",
                    transaction={"ts": ts},
                    timestamp=ts,
                )
                store.add_block(proposal)
                prev_a = proposal.block_hash

                agreement = create_half_block(
                    identity=id_b,
                    sequence_number=i + 1,
                    link_public_key=id_a.pubkey_hex,
                    link_sequence_number=i + 1,
                    previous_hash=prev_b,
                    block_type="agreement",
                    transaction={"ts": ts},
                    timestamp=ts + 1,
                )
                store.add_block(agreement)
                prev_b = agreement.block_hash

            # Compare scores from the shared store.
            engine = TrustEngine(store)

            integrity_a = engine.compute_chain_integrity(id_a.pubkey_hex)
            expected_integrity_a = vec["scores_a"]["integrity"]

            assert abs(integrity_a - expected_integrity_a) < 1e-6, (
                f"Integrity A: Python={integrity_a} vs Rust={expected_integrity_a}"
            )

            integrity_b = engine.compute_chain_integrity(id_b.pubkey_hex)
            expected_integrity_b = vec["scores_b"]["integrity"]

            assert abs(integrity_b - expected_integrity_b) < 1e-6, (
                f"Integrity B: Python={integrity_b} vs Rust={expected_integrity_b}"
            )
